
package com.company.myproject1.ui.desktop;


import com.company.myproject1.ui.views.login.Login;
import com.vaadin.ui.CustomComponent;
import com.xdev.ui.XdevButton;
import com.xdev.ui.XdevGridLayout;
import com.xdev.ui.XdevLabel;
import com.xdev.ui.XdevTextField;
import com.xdev.ui.XdevView;

public class MainView extends XdevView {

	/**
	 *
	 */
	public MainView() {
		super();
		this.initUI();

		setContent(new Login());
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.gridLayout = new XdevGridLayout();
		this.button = new XdevButton();
		this.label = new XdevLabel();
		this.textField = new XdevTextField();
		this.button2 = new XdevButton();

		this.button.setCaption("Button");
		this.label.setValue("Label");
		this.textField.setColumns(5);
		this.button2.setCaption("Button");

		this.gridLayout.setColumns(4);
		this.gridLayout.setRows(4);
		this.button.setSizeUndefined();
		this.gridLayout.addComponent(this.button, 0, 0);
		this.label.setSizeUndefined();
		this.gridLayout.addComponent(this.label, 1, 0);
		this.textField.setSizeUndefined();
		this.gridLayout.addComponent(this.textField, 1, 1);
		this.button2.setSizeUndefined();
		this.gridLayout.addComponent(this.button2, 2, 2);
		final CustomComponent gridLayout_hSpacer = new CustomComponent();
		gridLayout_hSpacer.setSizeFull();
		this.gridLayout.addComponent(gridLayout_hSpacer, 3, 0, 3, 2);
		this.gridLayout.setColumnExpandRatio(3, 1.0F);
		final CustomComponent gridLayout_vSpacer = new CustomComponent();
		gridLayout_vSpacer.setSizeFull();
		this.gridLayout.addComponent(gridLayout_vSpacer, 0, 3, 2, 3);
		this.gridLayout.setRowExpandRatio(3, 1.0F);
		this.gridLayout.setSizeFull();
		this.setContent(this.gridLayout);
		this.setSizeFull();
	} // </generated-code>

	// <generated-code name="variables">
	private XdevButton button, button2;
	private XdevLabel label;
	private XdevGridLayout gridLayout;
	private XdevTextField textField;
	// </generated-code>

}
